//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAMARSA.AGMA.ACUERDOCOMERCIAL.Resource {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceGrillas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGrillas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TRAMARSA.AGMA.ACUERDOCOMERCIAL.Resource.ResourceGrillas", typeof(ResourceGrillas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3832A03A-AA4B-4175-94AF-1E96AD895603.
        /// </summary>
        internal static string IdGrilla_AdminTipoContenedor {
            get {
                return ResourceManager.GetString("IdGrilla_AdminTipoContenedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7EC38F82-E3B0-4757-B362-5C8F7EBE4FC9.
        /// </summary>
        internal static string IdGrilla_BusquedaUsuarios {
            get {
                return ResourceManager.GetString("IdGrilla_BusquedaUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 407A472C-4B7A-4DD5-83A5-19F5B78B6E36.
        /// </summary>
        internal static string IdGrilla_ConsultaACEscalonado {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaACEscalonado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a B36E52FB-1E90-4F77-871A-CCF069D20D42.
        /// </summary>
        internal static string IdGrilla_ConsultaACLocal {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaACLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6B6C4707-D1AA-4A21-BE0E-B9FCDBD8BFB6.
        /// </summary>
        internal static string IdGrilla_ConsultaBandejaNotificacionIntegracion {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaBandejaNotificacionIntegracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CD2C022A-E498-4A3E-8CDF-C835A0339DC6.
        /// </summary>
        internal static string IdGrilla_ConsultaCliente {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6AFA2882-7BEF-4742-B49A-98DFECE2C4DD.
        /// </summary>
        internal static string IdGrilla_ConsultaClienteMatchCode {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaClienteMatchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 69A1584C-D5EF-454F-8476-9F31A959B90A.
        /// </summary>
        internal static string IdGrilla_ConsultaDepositoDefault {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaDepositoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 18B0EDD8-1287-4ED9-84BF-4FFC9FBFFCC7.
        /// </summary>
        internal static string IdGrilla_ConsultaDocumentoOrigen {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaDocumentoOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FE1D26D5-6DAD-42EB-AB3A-E20A00135C64.
        /// </summary>
        internal static string IdGrilla_ConsultaHistorialACEscalonado {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaHistorialACEscalonado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a B91C77DB-BCF3-426F-8105-00AA6566194D.
        /// </summary>
        internal static string IdGrilla_ConsultaHistorialACLocal {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaHistorialACLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a D9E4324A-F819-4BFA-B028-3100535B0F26.
        /// </summary>
        internal static string IdGrilla_ConsultaHistorialTarifaEscalonada {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaHistorialTarifaEscalonada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 95F77B50-18A0-43F0-9B0C-62505E57F695.
        /// </summary>
        internal static string IdGrilla_ConsultaHistorialTarifaLocal {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaHistorialTarifaLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 02d9bb68-8228-4742-a825-638b4caf33fa.
        /// </summary>
        internal static string IdGrilla_ConsultaMonitorCoparn {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaMonitorCoparn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 77EB45AF-2235-4257-950D-5EB797CE2DDD.
        /// </summary>
        internal static string IdGrilla_ConsultaNave {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaNave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3601365D-2DD9-46B6-A021-D38D309DBB0C.
        /// </summary>
        internal static string IdGrilla_ConsultaNoProcesados {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaNoProcesados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 55539F84-B4C2-446E-884C-27D6899DC15F.
        /// </summary>
        internal static string IdGrilla_ConsultaPartidaArancelaria {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaPartidaArancelaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FE65F132-8A28-4BA1-8D16-D1CADE8AFB99.
        /// </summary>
        internal static string IdGrilla_ConsultaPuerto {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaPuerto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 58E3C1BA-EAA7-499D-993B-554FACB8FE92.
        /// </summary>
        internal static string IdGrilla_ConsultarDetalleGrupoPuertoExterno {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultarDetalleGrupoPuertoExterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a B5AA03D4-3E30-4F54-91F5-32C887C8FEED.
        /// </summary>
        internal static string IdGrilla_ConsultarDetalleTipoContenedorExterno {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultarDetalleTipoContenedorExterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AAAF142C-E3B5-4F27-A570-8BB3AFEEB493.
        /// </summary>
        internal static string IdGrilla_ConsultarGrupoPuerto {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultarGrupoPuerto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EB71C41A-8056-475F-8674-5157DB3B1A77.
        /// </summary>
        internal static string IdGrilla_ConsultaServicioBl {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaServicioBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C293C8DE-4D2D-4B54-84F4-39F4F0B4E6CF.
        /// </summary>
        internal static string IdGrilla_ConsultaTarifa {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CBA3AF78-2490-4083-97B9-B47ADBC46BE1.
        /// </summary>
        internal static string IdGrilla_ConsultaTarifaEscalonada {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaTarifaEscalonada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F478BBE4-1DD1-4F5D-A484-FB4D7D030165.
        /// </summary>
        internal static string IdGrilla_ConsultaTarifaGeneral {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaTarifaGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10E91FE3-09A7-4ACE-A9F3-D34D4460B814.
        /// </summary>
        internal static string IdGrilla_ConsultaTarifaLocal {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaTarifaLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 01FD2ABF-68BF-49B0-A0CD-CCFC416418F3.
        /// </summary>
        internal static string IdGrilla_ConsultaTipoContenedor {
            get {
                return ResourceManager.GetString("IdGrilla_ConsultaTipoContenedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0633C936-7DE1-465E-8FBB-B5793E9A5610.
        /// </summary>
        internal static string IdGrilla_ListaconfiguracionLinea {
            get {
                return ResourceManager.GetString("IdGrilla_ListaconfiguracionLinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a D31FEBD5-D350-4959-BA1B-7ADB6A80492C.
        /// </summary>
        internal static string IdGrilla_ListaReporteACEscalonado {
            get {
                return ResourceManager.GetString("IdGrilla_ListaReporteACEscalonado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7FEE114B-F023-45BE-87B6-233EB1BDFFD1.
        /// </summary>
        internal static string IdGrilla_ListaReporteACLocal {
            get {
                return ResourceManager.GetString("IdGrilla_ListaReporteACLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A7BFECE3-7865-406E-AE85-B0D0631F6D85.
        /// </summary>
        internal static string IdGrilla_ListaReporteTarifaEscalonada {
            get {
                return ResourceManager.GetString("IdGrilla_ListaReporteTarifaEscalonada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7275950D-31EE-44DB-9336-FB5AB8F153E3.
        /// </summary>
        internal static string IdGrilla_ListaReporteTarifaLocal {
            get {
                return ResourceManager.GetString("IdGrilla_ListaReporteTarifaLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3E51F306-5F4E-4E87-8B00-4890829A63C7.
        /// </summary>
        internal static string IdGrilla_PesoVariable {
            get {
                return ResourceManager.GetString("IdGrilla_PesoVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2A64C309-04CB-4428-B008-BE08F2B8C548.
        /// </summary>
        internal static string IdGrilla_ReporteContenedorNoDevuelto {
            get {
                return ResourceManager.GetString("IdGrilla_ReporteContenedorNoDevuelto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 608211B8-795B-4A7A-A6C1-CEF7862EEFD1.
        /// </summary>
        internal static string IdGrilla_SeguimientoACEscalonado {
            get {
                return ResourceManager.GetString("IdGrilla_SeguimientoACEscalonado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1F188C36-C1C2-4159-A651-229067043C4C.
        /// </summary>
        internal static string IdGrilla_SeguimientoACLocal {
            get {
                return ResourceManager.GetString("IdGrilla_SeguimientoACLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1F128891-EBA6-451C-9917-1123B9ACFFA9.
        /// </summary>
        internal static string IdGrilla_TipoContenedorExterno {
            get {
                return ResourceManager.GetString("IdGrilla_TipoContenedorExterno", resourceCulture);
            }
        }
    }
}
